/// Champion-shape anti-cheat baseline.
///
/// This module implements the quarantine gate for submissions that are
/// faster than the reference champion by >2%. The reference champion
/// represents the best-known wheel shape for each track, typically
/// generated by ML-driven tuning (CMA-ES) over parametric wheel shapes.
///
/// Submissions faster than the champion by more than 2% are quarantined
/// for human review, as they likely represent cheating or a bug rather
/// than legitimate skill.
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

/// Champion reference data for a single track.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChampionReference {
    /// Track ID (matches numeric_id in track JSON)
    pub track_id: u16,
    /// Track name (for logging/debugging)
    pub track_name: String,
    /// Best known time for this track (milliseconds)
    pub best_time_ms: u32,
    /// The wheel polygon that achieved this time
    pub wheel: ChampionWheel,
    /// Physics version when this champion was recorded
    pub physics_version: u32,
    /// When this champion was recorded
    pub created_at: String,
    /// Notes on how this champion was generated
    pub notes: String,
}

/// Wheel polygon data from a champion run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChampionWheel {
    /// Swap tick (0 for initial wheel)
    pub swap_tick: u32,
    /// Number of vertices
    pub vertex_count: u8,
    /// Polygon vertices (relative to centroid, in 1/100 px units)
    pub polygon_vertices: Vec<(i16, i16)>,
}

/// Top-level structure of reference-champion.json.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChampionData {
    /// Format version
    pub version: u32,
    /// When this file was last updated
    pub updated_at: String,
    /// Map of track_id -> champion data (keys are strings for JSON)
    pub champions: HashMap<String, ChampionReference>,
}

/// Champion validation state.
#[derive(Debug, Clone)]
pub struct ChampionValidator {
    /// Loaded champion data
    data: ChampionData,
    /// Quarantine threshold as a percentage (e.g., 2.0 = 2%)
    quarantine_threshold_percent: f64,
}

impl ChampionValidator {
    /// Load champion data from the default location.
    ///
    /// Looks for reference-champion.json in:
    /// 1. CHAMPION_JSON_PATH environment variable
    /// 2. crates/validator/reference-champion.json (relative to workspace root)
    /// 3. /etc/drawrace/reference-champion.json
    pub fn load() -> Result<Self> {
        let path = Self::find_champion_path()?;
        Self::load_from_path(&path)
    }

    /// Load champion data from a specific path.
    pub fn load_from_path(path: &PathBuf) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("Failed to read champion file: {}", path.display()))?;

        let data: ChampionData = serde_json::from_str(&content)
            .with_context(|| format!("Failed to parse champion file: {}", path.display()))?;

        Ok(Self {
            data,
            quarantine_threshold_percent: 2.0,
        })
    }

    /// Find the champion JSON file.
    fn find_champion_path() -> Result<PathBuf> {
        // Check environment variable first
        if let Ok(env_path) = std::env::var("CHAMPION_JSON_PATH") {
            let path = PathBuf::from(&env_path);
            if path.exists() {
                return Ok(path);
            }
        }

        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string());

        // Compute workspace root
        let workspace_root = PathBuf::from(&manifest_dir)
            .parent() // crates
            .and_then(|p| p.parent()) // workspace root
            .map(|p| p.display().to_string())
            .unwrap_or(".".to_string());

        // List of paths to try
        let candidates = vec![
            format!(
                "{}/crates/validator/reference-champion.json",
                workspace_root
            ),
            format!(
                "{}/../../crates/validator/reference-champion.json",
                manifest_dir
            ),
            "crates/validator/reference-champion.json".to_string(),
            "/etc/drawrace/reference-champion.json".to_string(),
        ];

        for path in candidates {
            let path_buf = PathBuf::from(&path);
            if path_buf.exists() {
                return Ok(path_buf);
            }
        }

        Err(anyhow::anyhow!(
            "Could not find reference-champion.json in any of the following locations: {:?}. \
             Set CHAMPION_JSON_PATH environment variable to override.",
            [
                "CHAMPION_JSON_PATH env",
                "crates/validator/reference-champion.json",
                "/etc/drawrace/reference-champion.json"
            ]
        ))
    }

    /// Check if a submission time should be quarantined.
    ///
    /// Returns `Err` if the submission is faster than the champion by more than
    /// the quarantine threshold (default 2%).
    ///
    /// # Arguments
    /// * `track_id` - The track ID
    /// * `finish_time_ms` - The submission's claimed finish time
    ///
    /// # Returns
    /// * `Ok(())` - Submission is within acceptable bounds
    /// * `Err(QuarantineReason)` - Submission should be quarantined
    pub fn check_submission(
        &self,
        track_id: u16,
        finish_time_ms: u32,
    ) -> Result<(), QuarantineReason> {
        let track_key = track_id.to_string();

        let champion = match self.data.champions.get(&track_key) {
            Some(c) => c,
            None => {
                // No champion reference for this track - allow submission
                tracing::debug!(track_id = %track_id, "No champion reference, allowing submission");
                return Ok(());
            }
        };

        // Calculate how much faster the submission is than the champion
        // Negative value = submission is slower (OK)
        // Positive value = submission is faster (potentially suspicious)
        let percent_faster = ((champion.best_time_ms as f64 - finish_time_ms as f64)
            / champion.best_time_ms as f64)
            * 100.0;

        if percent_faster > self.quarantine_threshold_percent {
            tracing::warn!(
                track_id = %track_id,
                champion_time_ms = champion.best_time_ms,
                submission_time_ms = finish_time_ms,
                percent_faster = percent_faster,
                "Submission faster than champion by >{}%, quarantining",
                self.quarantine_threshold_percent
            );

            return Err(QuarantineReason {
                track_id,
                champion_best_time_ms: champion.best_time_ms,
                submission_time_ms: finish_time_ms,
                percent_faster,
                threshold_percent: self.quarantine_threshold_percent,
            });
        }

        Ok(())
    }

    /// Get the champion reference for a track, if available.
    #[allow(dead_code)]
    pub fn get_champion(&self, track_id: u16) -> Option<&ChampionReference> {
        self.data.champions.get(&track_id.to_string())
    }

    /// Set a custom quarantine threshold (default is 2.0).
    #[allow(dead_code)]
    pub fn with_quarantine_threshold(mut self, threshold: f64) -> Self {
        self.quarantine_threshold_percent = threshold;
        self
    }
}

/// Reason why a submission was quarantined.
#[derive(Debug, Clone)]
pub struct QuarantineReason {
    pub track_id: u16,
    pub champion_best_time_ms: u32,
    pub submission_time_ms: u32,
    pub percent_faster: f64,
    pub threshold_percent: f64,
}

impl std::fmt::Display for QuarantineReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Submission ({}ms) is {:.2}% faster than champion reference ({}ms) on track {}, exceeding {:.2}% threshold",
            self.submission_time_ms,
            self.percent_faster,
            self.champion_best_time_ms,
            self.track_id,
            self.threshold_percent
        )
    }
}

impl std::error::Error for QuarantineReason {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_champion_data() {
        let json = r#"{
            "version": 1,
            "updated_at": "2026-05-23T00:00:00Z",
            "champions": {
                "1": {
                    "track_id": 1,
                    "track_name": "Scribble Slope",
                    "best_time_ms": 28441,
                    "wheel": {
                        "swap_tick": 0,
                        "vertex_count": 12,
                        "polygon_vertices": [[-50, -50], [50, -50]]
                    },
                    "physics_version": 4,
                    "created_at": "2026-05-23T00:00:00Z",
                    "notes": "Test champion"
                }
            }
        }"#;

        let data: ChampionData = serde_json::from_str(json).unwrap();
        assert_eq!(data.version, 1);
        assert_eq!(data.champions.len(), 1);

        let champion = &data.champions["1"];
        assert_eq!(champion.track_id, 1);
        assert_eq!(champion.best_time_ms, 28441);
    }

    #[test]
    fn test_quarantine_threshold() {
        let json = r#"{
            "version": 1,
            "updated_at": "2026-05-23T00:00:00Z",
            "champions": {
                "1": {
                    "track_id": 1,
                    "track_name": "Test Track",
                    "best_time_ms": 30000,
                    "wheel": {
                        "swap_tick": 0,
                        "vertex_count": 12,
                        "polygon_vertices": [[-50, -50], [50, -50]]
                    },
                    "physics_version": 4,
                    "created_at": "2026-05-23T00:00:00Z",
                    "notes": "Test"
                }
            }
        }"#;

        let data: ChampionData = serde_json::from_str(json).unwrap();
        let validator = ChampionValidator {
            data,
            quarantine_threshold_percent: 2.0,
        };

        // Submission slower than champion - should pass
        assert!(validator.check_submission(1, 31000).is_ok());

        // Submission exactly at champion time - should pass
        assert!(validator.check_submission(1, 30000).is_ok());

        // Submission 1% faster - should pass
        assert!(validator.check_submission(1, 29700).is_ok());

        // Submission exactly 2% faster - should pass (boundary)
        assert!(validator.check_submission(1, 29400).is_ok());

        // Submission 2.1% faster - should quarantine
        let result = validator.check_submission(1, 29370);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert_eq!(err.track_id, 1);
        assert_eq!(err.champion_best_time_ms, 30000);
        assert_eq!(err.submission_time_ms, 29370);
        assert!(err.percent_faster > 2.0);
    }

    #[test]
    fn test_no_champion_for_track() {
        let json = r#"{
            "version": 1,
            "updated_at": "2026-05-23T00:00:00Z",
            "champions": {}
        }"#;

        let data: ChampionData = serde_json::from_str(json).unwrap();
        let validator = ChampionValidator {
            data,
            quarantine_threshold_percent: 2.0,
        };

        // No champion for track 99 - should allow any submission
        assert!(validator.check_submission(99, 1000).is_ok());
    }
}
